// app/about/page.tsx
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export default function AboutPage() {
  return (
    <main className="font-sans text-[16px] font-light text-[#333]">
      {/* Hero */}
      <section className="bg-[#051C2C] py-16 lg:py-24">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px]">
          <h1 className="font-serif text-[44px] lg:text-[52px] font-light text-white leading-tight mb-6">
            About BITZ
          </h1>
          <p className="text-white/70 text-lg max-w-2xl">
            A technology consulting firm with proven delivery capability.
          </p>
        </div>
      </section>

      {/* Section 1: Company Overview */}
      <section className="bg-white py-16 lg:py-20">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px]">
          <p className="text-lg leading-relaxed max-w-3xl mb-12">
            BITZ is a technology consulting firm. We design, build, and operate
            digital systems for public institutions and enterprises in Africa.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8 mb-12">
            <div>
              <h3 className="font-serif text-[20px] font-light text-[#051C2C] mb-6">
                Focus areas
              </h3>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  Government digital transformation
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  Health information systems
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  Financial services infrastructure
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  Social protection platforms
                </li>
              </ul>
            </div>

            <div>
              <h3 className="font-serif text-[20px] font-light text-[#051C2C] mb-6">
                Geographic scope
              </h3>
              <p>Kenya, Uganda, Tanzania, Lesotho, Somalia</p>
            </div>
          </div>
        </div>
      </section>

      {/* Section 2: Mission */}
      <section className="bg-[#F8FAFC] py-16 lg:py-20">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px]">
          <blockquote className="font-serif text-[32px] lg:text-[40px] font-light text-[#051C2C] leading-tight max-w-4xl">
            &ldquo;To build reliable digital infrastructure for institutions
            that serve the public.&rdquo;
          </blockquote>
        </div>
      </section>

      {/* Section 3: Track Record */}
      <section className="bg-white py-16 lg:py-20">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px]">
          <h2 className="font-serif text-[32px] lg:text-[40px] font-light text-[#051C2C] mb-12">
            Track record
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Recognition */}
            <div className="bg-white border border-[#E2E8F0] p-6">
              <h3 className="font-serif text-[20px] font-light text-[#051C2C] mb-6">
                Recognition
              </h3>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  UNICEF Venture Fund recipient
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  KDEAP Digital Assessment completed
                </li>
              </ul>
            </div>

            {/* Operational Systems */}
            <div className="bg-white border border-[#E2E8F0] p-6">
              <h3 className="font-serif text-[20px] font-light text-[#051C2C] mb-6">
                Operational Systems
              </h3>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  Child Helpline Systems (116): Five countries, 24/7 operations
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  OPENHMIS: Health records platform deployed across multiple
                  facilities
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  Tower SACCO: Member management system for financial cooperative
                </li>
              </ul>
            </div>

            {/* Scale */}
            <div className="bg-white border border-[#E2E8F0] p-6">
              <h3 className="font-serif text-[20px] font-light text-[#051C2C] mb-6">
                Scale
              </h3>
              <ul className="space-y-3">
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  <strong>50,000+</strong> patient records digitized
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  <strong>5,000+</strong> financial members managed
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2251FF] mt-1.5 shrink-0">&#8212;</span>
                  <strong>10,000+</strong> monthly crisis calls handled
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Section 4: Differentiation */}
      <section className="bg-[#051C2C] text-white py-16 lg:py-20">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px]">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="font-serif text-[24px] font-light mb-4">
                We build systems that operate.
              </h3>
              <p className="text-white/70">
                Many firms design. We implement, deploy, and run national-scale
                platforms.
              </p>
            </div>

            <div>
              <h3 className="font-serif text-[24px] font-light mb-4">
                Multi-country experience.
              </h3>
              <p className="text-white/70">
                We understand the operational realities of deploying systems
                across borders, regulatory environments, and infrastructure
                constraints.
              </p>
            </div>

            <div>
              <h3 className="font-serif text-[24px] font-light mb-4">
                Public sector focus.
              </h3>
              <p className="text-white/70">
                We work with governments and institutions where reliability,
                security, and compliance are non-negotiable.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Section 5: Delivery Approach */}
      <section className="bg-white py-16 lg:py-20">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px]">
          <h2 className="font-serif text-[32px] lg:text-[40px] font-light text-[#051C2C] mb-12">
            Delivery approach
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-0">
            {[
              {
                step: "01",
                title: "Design",
                subtitle: "Technical architecture, feasibility, planning",
              },
              {
                step: "02",
                title: "Build",
                subtitle: "Development, integration, testing",
              },
              {
                step: "03",
                title: "Deploy",
                subtitle: "Installation, training, go-live",
              },
              {
                step: "04",
                title: "Operate",
                subtitle: "24/7 support, maintenance, evolution",
              },
            ].map((phase, index) => (
              <div
                key={phase.step}
                className="relative border border-[#E2E8F0] p-6"
              >
                {index < 3 && (
                  <div className="hidden md:flex absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/2 z-10 w-6 h-6 bg-[#2251FF] items-center justify-center">
                    <ArrowRight className="w-3 h-3 text-white" />
                  </div>
                )}
                <p className="text-[14px] font-medium text-[#2251FF] mb-2">
                  {phase.step}
                </p>
                <h3 className="font-serif text-[24px] font-light text-[#051C2C] mb-3">
                  {phase.title}
                </h3>
                <p className="text-[#333]/70 text-[15px]">{phase.subtitle}</p>
              </div>
            ))}
          </div>

          <p className="mt-8 text-[#333]/70 text-[15px]">
            Each phase is documented, transparent, and measured against
            operational outcomes.
          </p>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#2251FF] text-white py-16">
        <div className="max-w-[1216px] mx-auto px-6 lg:px-[108px] text-center">
          <h2 className="font-serif text-[32px] lg:text-[40px] font-light mb-8">
            Discuss a project
          </h2>
          <Link
            href="/contact"
            className="inline-flex items-center gap-2 bg-white text-[#051C2C] px-6 py-3 text-[16px] font-medium hover:bg-white/90 transition-colors"
          >
            Request Consultation
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>
    </main>
  );
}

// bitz/src/pages/About.vue
<template>
  <div class="about bg-background text-text-primary font-sans">
    <!-- Hero Section -->
    <section class="bg-primary text-white pt-32 pb-20">
      <div class="container-custom mx-auto px-6">
        <div class="max-w-3xl">
          <p class="text-secondary font-bold uppercase tracking-widest text-sm mb-4">About BITZ</p>
          <h1 class="text-4xl md:text-5xl font-bold leading-tight mb-8">
            Technology systems for public institutions and enterprises
          </h1>
          <p class="text-xl text-slate-300 leading-relaxed">
            BITZ is a technology consulting firm. We design, build, and operate digital systems for public institutions and enterprises in Africa.
          </p>
        </div>
      </div>
    </section>

    <!-- Mission Section -->
    <section class="py-24 bg-white border-b border-slate-200">
      <div class="container-custom mx-auto px-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
          <div>
            <h2 class="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Our Mission</h2>
            <p class="text-3xl font-bold text-primary leading-tight">
              To build reliable digital infrastructure for institutions that serve the public.
            </p>
          </div>
          <div class="space-y-6">
            <p class="text-lg text-text-secondary">
              We focus on areas where reliability, security, and compliance are non-negotiable:
            </p>
            <ul class="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <li v-for="focus in focusAreas" :key="focus" class="flex items-center gap-3 font-medium text-primary">
                <div class="w-1.5 h-1.5 bg-secondary rounded-full"></div>
                {{ focus }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Track Record / Achievements -->
    <section class="py-24 bg-background">
      <div class="container-custom mx-auto px-6">
        <div class="mb-16">
          <h2 class="text-3xl font-bold text-primary mb-4">Track Record</h2>
          <p class="text-text-secondary">Proven delivery capability at national scale.</p>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div v-for="achievement in achievements" :key="achievement.id" class="bg-white border border-slate-200 p-8 rounded-sm">
            <div class="text-4xl font-bold text-secondary mb-2">{{ achievement.value }}</div>
            <div class="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">{{ achievement.label }}</div>
            <h3 class="text-lg font-bold mb-2 text-primary">{{ achievement.title }}</h3>
            <p class="text-sm text-text-secondary leading-relaxed">{{ achievement.description }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Differentiation -->
    <section class="py-24 bg-white">
      <div class="container-custom mx-auto px-6">
        <h2 class="text-3xl font-bold text-primary mb-12">Why BITZ?</h2>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-12">
          <div class="space-y-4">
            <h4 class="font-bold text-xl text-primary">We build systems that operate.</h4>
            <p class="text-text-secondary">Many firms design. We implement, deploy, and run national-scale platforms with 24/7 availability.</p>
          </div>
          <div class="space-y-4">
            <h4 class="font-bold text-xl text-primary">Multi-country experience.</h4>
            <p class="text-text-secondary">We understand the operational realities of deploying systems across borders, regulatory environments, and infrastructure constraints.</p>
          </div>
          <div class="space-y-4">
            <h4 class="font-bold text-xl text-primary">Public sector focus.</h4>
            <p class="text-text-secondary">We work with governments and institutions where reliability, security, and compliance are non-negotiable.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Delivery Approach -->
    <section class="py-24 bg-navy-900 text-white">
      <div class="container-custom mx-auto px-6">
        <div class="mb-16 text-center">
          <h2 class="text-3xl font-bold mb-4">Delivery Approach</h2>
          <p class="text-slate-400">Our documented and transparent implementation methodology.</p>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div v-for="(step, index) in deliverySteps" :key="step.title" class="relative">
            <div class="text-6xl font-bold text-white/5 absolute -top-8 -left-4">{{ index + 1 }}</div>
            <h4 class="font-bold text-xl mb-4 text-secondary">{{ step.title }}</h4>
            <p class="text-slate-400 text-sm leading-relaxed">{{ step.description }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Leadership Placeholder -->
    <section class="py-24 bg-white">
      <div class="container-custom mx-auto px-6 text-center">
        <h2 class="text-3xl font-bold text-primary mb-6">Discuss a project</h2>
        <p class="text-text-secondary mb-10 max-w-2xl mx-auto">
          Our leadership team brings deep domain expertise in public sector systems and enterprise-grade technical delivery.
        </p>
        <router-link to="/contact" class="px-8 py-4 bg-primary text-white font-bold rounded hover:bg-navy-800 transition-all">
          Request Consultation
        </router-link>
      </div>
    </section>
  </div>
</template>

<script setup>
import { achievementsData } from '@/utils/Achievements'

const achievements = achievementsData
const focusAreas = [
  "Government digital transformation",
  "Health information systems",
  "Financial services infrastructure",
  "Social protection platforms"
]

const deliverySteps = [
  { title: "Design", description: "Technical architecture, feasibility, and operational planning." },
  { title: "Build", description: "Development, systems integration, and rigorous testing." },
  { title: "Deploy", description: "Installation, comprehensive training, and go-live support." },
  { title: "Operate", description: "24/7 support, maintenance, and continuous evolution." }
]
</script>

<style scoped>
.container-custom {
  max-width: 1200px;
}
</style>
